In [80]:
import pandas as pd

In [81]:
df = pd.read_csv("SampleSuperstore.csv")
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [82]:
inputs = df.drop('Profit',axis='columns')

In [83]:
target = df['Profit']

In [84]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [85]:
inputs['Segment_n'] = le_company.fit_transform(inputs['Segment'])
inputs['City_n'] = le_job.fit_transform(inputs['City'])

In [86]:
inputs

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Segment_n,City_n
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,0,194
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,0,194
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,1,266
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,0,153
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,0,153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,0,295
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,0,104
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,0,104
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,0,104
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,0,517

In [87]:
inputs_n = inputs.drop(['Segment','City'],axis='columns')

In [88]:
inputs_n

,Ship Mode,Country,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Segment_n,City_n
0,Second Class,United States,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,0,194
1,Second Class,United States,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,0,194
2,Second Class,United States,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,1,266
3,Standard Class,United States,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,0,153
4,Standard Class,United States,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,0,153
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,United States,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,0,295
9990,Standard Class,United States,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,0,104
9991,Standard Class,United States,California,92627,West,Technology,Phones,258.5760,2,0.20,0,104
9992,Standard Class,United States,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,0,104
9993,Second Class,United States,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,0,517

In [89]:
target

0        41.9136
1       219.5820
2         6.8714
3      -383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [90]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\python anaconda\lib\site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in d:\python anaconda\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in d:\python anaconda\lib\site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.1.1 in d:\python anaconda\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\python anaconda\lib\site-packages (from scikit-learn) (2.2.0)

In [91]:
import pandas as pd

In [92]:
from sklearn.tree import DecisionTreeClassifier

In [93]:
data = {
    'feature1': [1.2, 2.3, 3.1, 4.5],
    'feature2': ['First Class', 'Second Class', 'Second Class', 'First Class'],
    'target': [0, 1, 0, 1]
}
df = pd.DataFrame(data)

In [94]:
inputs_n = df.drop('target', axis=1)

In [95]:
target = df['target']

In [96]:
label_encoder = LabelEncoder()
inputs_n['feature2'] = label_encoder.fit_transform(inputs_n['feature2'])

In [97]:
inputs_n = inputs_n.fillna(inputs_n.mean())

In [98]:
from sklearn import tree

In [99]:
model = tree.DecisionTreeClassifier()

In [100]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [101]:
model.score(inputs_n,target)

1.0

In [102]:
model.predict([[2,1]])

D:\python anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [103]:
model.predict([[2,1]])

D:\python anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)